### PR TITLE
0.8.0-SNAPSHOT: preparing for play-2.4

### PR DESCRIPTION
**Pull request by helllamer**
$SUBJ

Unsure about removing lines for zeroing `lessEntryPoints` and `javascriptEntryPoints`. Cannot find any alternatives. Disabling only by removing `sbt-less` and other `sbt-web` plugins from `myproj1/project/plugins.sbt`.

### CODE REVIEW

**Comment by akkie** [comment]
Is there any progress on this issue? It's been a week since Play 2.4 is final.

**Comment by OliverKK** [comment]
+1

**Comment by derfloscher** [comment]
+1

**Comment by Shiti** [comment]
added support for Play 2.4.0

**Pull request closed without merging**
